### ISSUE TITLE
Property "Craft\WebApp.upsShippingRates_shippingMethods" is not defined

### ISSUE THREAD

**Issue by Amiga4ever** [surprisehighway/craft-upsshippingrates#3]
I've went through installation process but when I go to Shipping Methods in commerce settings I receive this error :(

Property "Craft\WebApp.upsShippingRates_shippingMethods" is not defined.
![screen shot 2018-06-08 at 12 33 46](https://user-images.githubusercontent.com/4464156/41156058-39024e40-6b18-11e8-8f90-901da5cd5b85.png)

**Comment by Amiga4ever** [comment]
Problem solved. Reinstalling plugin fix the issue...

**Comment by Amiga4ever** [comment]
But now I can't see UPS Shipping Method on checkout page..shouldn't appear by default as rest of the methods? Is  this plugin req PHP 5.5+ ? My server has 5.4 and throwing error
Call to undefined function GuzzleHttp\Handler\curl_reset() in .../craft/plugins/upsshippingrates/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

**Comment by siffring** [comment]
Sorry for the trouble. Did you complete the [configuration steps](https://github.com/surprisehighway/craft-upsshippingrates#configuring-ups-shipping-rates) after you installed the plugin?

If so, go to your shipping settings and see if the UPS options appear like in the [screenshot here](https://github.com/surprisehighway/craft-upsshippingrates#using-ups-shipping-rates-in-craft-commerce).

**Comment by Amiga4ever** [comment]
Hi,
Yes it is visible on Shipping Method tab.  All is configured. I'm thinking
that is PHP problem. Some ppl had this problem and upgrading php to 5.5
solved the problem...
I will try tomorrow cheers

pt., 8 cze 2018, 18:51 użytkownik Jason Siffring <notifications@github.com>
napisał:

**Comment by siffring** [comment]
OK that's possible. Please let us know if going to 5.5 fixes it and we'll make a note of that in the documentation.

**Comment by Amiga4ever** [comment]
I can confirm on PHP5.5+ i don't have this issue anymore.
